[Draft First table]: Source Recurly: Add dbt converter
airbytehq/airbyte-dbt-models pull request #46
Opened 2024-08-08 18:25 UTC by btkcodedev

Closes https://github.com/airbytehq/airbyte-dbt-models/issues/24

**How**
1) The tables from the fivetran model are analyzed for source-recurly
https://github.com/fivetran/dbt_recurly_source/tree/main/models

2) Fivertran's Streams were matched against Airbyte streams and differential tables were identified
3) Single transformation for the table `account_balance` is made from the account stream

Raising 1st draft PR for review

2024-08-08 18:27 UTC, btkcodedev commented
Current analysis: @marcosmarxm 

URL: https://fivetran.github.io/dbt_recurly/#!/model/model.recurly_source

| **Fivetran**                                    | **Airbyte**            |
|-------------------------------------------------|------------------------|
| `stg_recurly__account_balance_history.sql`      | Trasformation from `accounts`  |
| `stg_recurly__account_history.sql`              | `accounts`  |
| `stg_recurly__account_note_history.sql`         | `account_notes`        |
| `stg_recurly__billing_info_history.sql`         | `billing_info`         |
| `stg_recurly__coupon_discount.sql`              | `coupons`              |
| `stg_recurly__coupon_redemption_history.sql`    | ❌ it doesn't exist         |
| `stg_recurly__credit_payment_history.sql`       | `credit_payments`      |
| `stg_recurly__invoice_coupon_redemption_history.sql` | ❌ it doesn't exist          |
| `stg_recurly__invoice_history.sql`              | `invoices`             |
| `stg_recurly__invoice_subscription_history.sql` | ❌ it doesn't exist       |
| `stg_recurly__line_item_history.sql`            | `line_items`           |
| `stg_recurly__plan_currency_history.sql`        | ❌ it doesn't exist                |
| `stg_recurly__plan_history.sql`                 | `plans`                |
| `stg_recurly__subscription_add_on_history.sql`  | ❌ it doesn't exist             |
| `stg_recurly__subscription_change_history.sql`  | ❌ it doesn't exist        |
| `stg_recurly__subscription_history.sql`         | `subscriptions`        |
| `stg_recurly__transaction.sql`                  | `transactions`         |
| `stg_recurly__transaction_subscription.sql`     | ❌ it doesn't exist        |

2024-08-08 18:51 UTC, btkcodedev commented
Waiting for the review @marcosmarxm with some comments :smiley_cat: 
![image](https://github.com/user-attachments/assets/59e5189b-3df3-4dfc-8f4c-dde2adf87bc1)

2024-08-08 19:15 UTC, btkcodedev commented
New models possible
Fivetran - coupon_redemption_history from Airbyte - account_coupon_redemptions

2024-08-08 19:18 UTC, btkcodedev commented
Currently, one transformation for account_balance from account has been done
New transformation possible, coupon_redemption_history from Airbyte - account_coupon_redemptions

Awaiting comment to verify, If I am going with the right path

2024-08-09 06:58 UTC, btkcodedev commented
@marcosmarxm, Please see the last commit, I've tried to add the account_coupon_redemptions source yaml
and do the transformation, but it shows it can't be found.
Is there anything I miss, or should I remove it,
Two possible transformations are done :heavy_check_mark:

2024-08-11 17:13 UTC, btkcodedev commented
Helloo,
I have a nested object for account id in schema account_coupon_redemptions how to add it to the source as columns?

stream: account_coupons_redemptions:
...
coupon:{
   id: "123"
},
account:{
   id: "345",
},
redemption_id: "12"


I've written directly like this, but not working | inside `source_recurly/source/account_coupon_redemptions.yaml`
![image](https://github.com/user-attachments/assets/417f4149-3a97-4012-ad7c-861be2ec1785)

2024-08-11 18:26 UTC, btkcodedev commented
Update: account_notes, billing_info, line_items, credit_payments, invoices left

2024-08-11 18:47 UTC, btkcodedev commented
Hi, @marcosmarxm, One doubt
Why is this error appearing as `not found`
Are my identifiers correct?
![image](https://github.com/user-attachments/assets/ccea00e3-45ad-43c1-9e66-b1276a60154d)

2024-08-12 18:33 UTC, marcosmarxm commented
@btkcodedev try to get it runnig with postgres for snowflake/bigquery it is a small config problem.

2024-08-13 18:52 UTC, btkcodedev commented
Current Update: @marcosmarxm 

URL: https://fivetran.github.io/dbt_recurly/#!/model/model.recurly_source

| **Fivetran**                                    | **Airbyte**            |
|-------------------------------------------------|------------------------|
| `stg_recurly__account_balance_history.sql`      | :heavy_check_mark:  Trasformation from `accounts`  |
| `stg_recurly__account_history.sql`              | :heavy_check_mark:  `accounts`  |
| `stg_recurly__account_note_history.sql`         | :heavy_check_mark:  `account_notes`        |
| `stg_recurly__billing_info_history.sql`         | :heavy_check_mark:  `billing_info`         |
| `stg_recurly__coupon_discount.sql`              | NULL table             |
| `stg_recurly__coupon_redemption_history.sql`    | :heavy_check_mark:  Transformation from `account_coupon_redemptions`       |
| `stg_recurly__credit_payment_history.sql`       | :heavy_check_mark:  `credit_payments`      |
| `stg_recurly__invoice_coupon_redemption_history.sql` | NULL table          |
| `stg_recurly__invoice_history.sql`              | NULL table            |
| `stg_recurly__invoice_subscription_history.sql` | NULL table    |
| `stg_recurly__line_item_history.sql`            | :heavy_check_mark:  `line_items`           |
| `stg_recurly__plan_currency_history.sql`        | NULL table            |
| `stg_recurly__plan_history.sql`                 | :heavy_check_mark:  `plans`                |
| `stg_recurly__subscription_add_on_history.sql`  | NULL table      |
| `stg_recurly__subscription_change_history.sql`  | :heavy_check_mark:  `subscriptions`      |
| `stg_recurly__subscription_history.sql`         | NULL table       |
| `stg_recurly__transaction.sql`                  |:heavy_check_mark:  `transactions`         |
| `stg_recurly__transaction_subscription.sql`     | NULL table     |

2024-08-13 19:39 UTC, marcosmarxm commented
What is the reasoning behind creating NULL tables, or is this something you're still updating?

2024-08-14 02:35 UTC, btkcodedev commented
@marcosmarxm, it would show error in Postgress as tables are not found, also there are no options for disabling it isn't it

Please correct if I am wrong

2024-08-15 12:21 UTC, marcosmarxm commented on connectors/source_recurly/models/fivetran_converter/credit_payment_history.sql
> +            NULL AS original_invoice_id,
Please check https://recurly.com/developers/api/v2021-02-25/index.html#operation/list_account_credit_payments

2024-08-15 16:23 UTC, btkcodedev commented on connectors/source_recurly/models/fivetran_converter/coupon_redemption_history.sql
> +            NULL AS coupon_id,
Yes, absolutely, Done :white_check_mark:

2024-08-15 16:24 UTC, btkcodedev commented on connectors/source_recurly/models/fivetran_converter/credit_payment_history.sql
> +            NULL AS action,
Done :white_check_mark:

2024-08-15 16:24 UTC, btkcodedev commented on connectors/source_recurly/models/fivetran_converter/credit_payment_history.sql
> +            NULL AS applied_to_invoice_id,
Done :white_check_mark:

2024-08-16 14:19 UTC, btkcodedev commented on connectors/source_recurly/models/fivetran_converter/invoice_subscription_history.sql
> +            NULL AS is_most_recent_record
Done ✅

2024-08-16 14:19 UTC, btkcodedev commented on connectors/source_recurly/models/fivetran_converter/invoice_history.sql
> +            NULL AS invoice_id,
Done ✅

2024-08-16 14:20 UTC, btkcodedev commented
Comments resolved, Please check @marcosmarxm :bowing_man:

2024-08-16 15:14 UTC, marcosmarxm requested changes
@btkcodedev please check my last commit I made two examples to you (`account_balance_history` and `account_history`). Please feel free to contact me if you have any further question.

2024-08-16 15:32 UTC, btkcodedev commented
Oh yes, Thanks, I'll try with others the same

2024-08-19 16:43 UTC, btkcodedev commented
@marcosmarxm, After 5 hours of frying my brain, I could see SQL errors clearing slowly :partying_face: 
- Used your example to fill other models and Added all possible values in place of null :white_check_mark: 
- All the Snowflake and Bigquery SQL queries are cleared, only those that shows are tables doesn't exist, Please comment on how to clear those
- In postgres, there are only two errors, but the table has those fields, Please comment on this too
![image](https://github.com/user-attachments/assets/18890669-f2b3-4f9c-b51f-58482d686a35)


Please continue to review :bowing_man:

2024-08-19 16:45 UTC, btkcodedev commented
In postgres error, user object is there and it has those fields
https://github.com/airbytehq/airbyte/blob/efd76b79d05bf96e5e66c72169c954e4639b4660/airbyte-integrations/connectors/source-recurly/source_recurly/manifest.yaml#L1126
Need comment on that

2024-08-20 21:53 UTC, marcosmarxm approved these changes
LGTM @btkcodedev there is a small change in CI to make run with bigquery and snowflake but the models looks awesome! Thanks for the contribution

2024-08-21 11:34 UTC, btkcodedev commented
:bow Please continue to merge if it's ready.

2024-08-28 16:52 UTC, merged