Create dbt converter for Airbyte Asana source connector
airbytehq/airbyte-dbt-models pull request #53
Opened 2024-08-14 18:00 UTC by pangeran-bottor

closes #9

2024-08-16 12:18 UTC, marcosmarxm requested changes

2024-08-16 12:18 UTC, marcosmarxm commented on connectors/source_asana/dbt_project.yml
> +profile: integration_tests
keep profile as airbyte

2024-08-16 12:18 UTC, marcosmarxm commented on connectors/source_asana/integration_tests/dbt_project.yml
> +    asana_schema: "airbyte_dbt_asana"
keep same level as the other variables.

2024-08-21 00:02 UTC, marcosmarxm requested changes

2024-08-21 00:02 UTC, marcosmarxm commented on connectors/source_asana/models/fivetran_converter/project.sql
> +    )
Nice start @pangeran-bottor you can use Chatgpt to translate to snowflake and postgres.

2024-08-22 17:26 UTC, marcosmarxm commented
Nice @pangeran-bottor I'm gonna review tomorrow! Sorry the delay

2024-08-26 19:40 UTC, marcosmarxm commented
@pangeran-bottor it looks good, missing a couple of models.

2024-08-27 14:46 UTC, pangeran-bottor commented
Thanks for the help @marcosmarxm 
Finalized this PR to be reviewed. The models already cover all Fivetran models from https://github.com/fivetran/dbt_asana_source/blob/main/models/src_asana.yml

2024-09-02 18:32 UTC, marcosmarxm approved these changes
Thanks a lot @pangeran-bottor the model is working now :)

2024-09-03 16:35 UTC, merged